server:
  port: 8000
spring:
  application:
    name: micro-dept # 微服务名字
eureka:
  client:
    service-url:
      #defaultZone: http://admin:admin@localhost:7000/eureka/
      defaultZone: http://admin:admin@www.eureka7000.com:7000/eureka/
    fetch-registry: false  # 检索服务
    prefer-ip-address: true
  instance:
    instance-id: ${spring.application.name}:${spring.cloud.client.ipAddress}:${server.port}
#    instance-id: ${spring.application.name}:${spring.cloud.client.ipAddress}:${spring.application.instance_id:${server.port}}
    prefer-ip-address: true
    status-page-url: http://www.baidu.com  # 自定义实例跳转链接  设置后 prefer-ip-address 无效了
    lease-renewal-interval-in-seconds: 5  #默认30秒  表示Eureka Client 发送心跳给server端的频率
    lease-expiration-duration-in-seconds: 5  #默认90秒   表示Eureka Server至上次收到 client的心跳之后，等待下一次心跳的超时时间，在这个时间内若没有收到下一次心跳，则移除该Intance

